# Generated by Django 3.2.4 on 2021-08-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='react_type',
            field=models.IntegerField(choices=[(1, 'like'), (2, 'dislike'), (3, 'smile'), (4, 'heart'), (5, 'thanks')], default=1),
        ),
    ]
