# Generated by Django 3.2.4 on 2021-08-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_react_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='react',
            unique_together={('user', 'comment'), ('user', 'post')},
        ),
    ]
